<?xml version="1.0" encoding="utf-8"?>
<ScriptDocument xmlns:i="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://progea.com">
  <bEnableLog>true</bEnableLog>
  <bEnableSysLog>true</bEnableSysLog>
  <breakpoints xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
  <currentStatusTag i:nil="true" />
  <cycleTimeTag i:nil="true" />
  <disableWhenNotUsed>true</disableWhenNotUsed>
  <fastSamplingInterval>500</fastSamplingInterval>
  <forceWritingOnServer>true</forceWritingOnServer>
  <id>00000000-0000-0000-0000-000000000000</id>
  <listVariableUsed xmlns:d2p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays">
    <d2p1:string>stopVar</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer00</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter00-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter00-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter00-FAULT</d2p1:string>
    <d2p1:string>statusVar_workstation_printerRack00</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer01</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter01-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter01-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter01-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer02</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter02-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter02-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter02-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer03</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter03-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter03-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter03-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer04</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter04-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter04-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter04-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer05</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter05-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter05-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter05-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer06</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter06-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter06-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter06-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer07</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter07-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter07-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter07-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer08</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter08-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter08-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter08-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer09</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter09-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter09-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter09-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer10</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter10-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter10-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter10-FAULT</d2p1:string>
    <d2p1:string>statusVar_workstation_printerRack01</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer11</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter11-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter11-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter11-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer12</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter12-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter12-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter12-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer13</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter13-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter13-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter13-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer14</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter14-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter14-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter14-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer15</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter15-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter15-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter15-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer16</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter16-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter16-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter16-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer17</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter17-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter17-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter17-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer18</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter18-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter18-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter18-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-printer19</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter19-IDLE</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter19-BUSY</d2p1:string>
    <d2p1:string>statusVar_printers_statusPrinter19-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-laserCutter00</d2p1:string>
    <d2p1:string>statusVar_laserCutter_statusLaserCutter00-IDLE</d2p1:string>
    <d2p1:string>statusVar_laserCutter_statusLaserCutter00-BUSY</d2p1:string>
    <d2p1:string>statusVar_laserCutter_statusLaserCutter00-FAULT</d2p1:string>
    <d2p1:string>statusVar_workstation_laserCutterWorkstation</d2p1:string>
    <d2p1:string>Station0_moviconSend-mobileRobot00</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot00-IDLE</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot00-BUSY</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot00-FAULT</d2p1:string>
    <d2p1:string>statusVar_workstation_mobileRobotFleet</d2p1:string>
    <d2p1:string>Station0_moviconSend-mobileRobot01</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot01-IDLE</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot01-BUSY</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot01-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-mobileRobot02</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot02-IDLE</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot02-BUSY</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobot02-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-cobot00</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobotCobot00-IDLE</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobotCobot00-BUSY</d2p1:string>
    <d2p1:string>statusVar_mobileRobot_statusMobileRobotCobot00-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-cobot01</d2p1:string>
    <d2p1:string>statusVar_cobot_statusCobot00-IDLE</d2p1:string>
    <d2p1:string>statusVar_cobot_statusCobot00-BUSY</d2p1:string>
    <d2p1:string>statusVar_cobot_statusCobot00-FAULT</d2p1:string>
    <d2p1:string>statusVar_workstation_cobotWorkstation</d2p1:string>
    <d2p1:string>Station0_moviconSend-cobot02</d2p1:string>
    <d2p1:string>statusVar_cobot_statusCobot01-IDLE</d2p1:string>
    <d2p1:string>statusVar_cobot_statusCobot01-BUSY</d2p1:string>
    <d2p1:string>statusVar_cobot_statusCobot01-FAULT</d2p1:string>
    <d2p1:string>Station0_moviconSend-quattro00</d2p1:string>
    <d2p1:string>statusVar_quattro_statusQuattro00-IDLE</d2p1:string>
    <d2p1:string>statusVar_quattro_statusQuattro00-BUSY</d2p1:string>
    <d2p1:string>statusVar_quattro_statusQuattro00-FAULT</d2p1:string>
    <d2p1:string>statusVar_workstation_quattroWorkstation</d2p1:string>
    <d2p1:string>Station0_moviconSend-viper00</d2p1:string>
    <d2p1:string>statusVar_viper_statusViper00-IDLE</d2p1:string>
    <d2p1:string>statusVar_viper_statusViper00-BUSY</d2p1:string>
    <d2p1:string>statusVar_viper_statusViper00-FAULT</d2p1:string>
    <d2p1:string>statusVar_workstation_viperWorkstation</d2p1:string>
    <d2p1:string>Station0_moviconSend-viper01</d2p1:string>
    <d2p1:string>statusVar_viper_statusViper01-IDLE</d2p1:string>
    <d2p1:string>statusVar_viper_statusViper01-BUSY</d2p1:string>
    <d2p1:string>statusVar_viper_statusViper01-FAULT</d2p1:string>
  </listVariableUsed>
  <maxCleanCount>2</maxCleanCount>
  <nSelLength>0</nSelLength>
  <nSleepTime>50</nSleepTime>
  <nStartSel>264</nStartSel>
  <publishingInterval>1000</publishingInterval>
  <removeDisabledItemAfterSecs>30</removeDisabledItemAfterSecs>
  <sCode>'#Language "WWB.NET"
Imports System
Imports System.Threading

Option Explicit

Const statCodeFault As Int16 = 0
Const statCodeIdle As Int16 = 1
Const statCodeBusy As Int16 = 2

Const sleepTime As Int16 = 2000

Sub Main Handles .Main
    stopVar = True
    Do
        ' DoEvents

        '
        ' Status for 3D Printers
        '
        ' Status for 3D Printer 00
        Select Case Station0_moviconSend.printer00
            Case statCodeIdle
                statusVar_printers_statusPrinter00.IDLE = True
                statusVar_printers_statusPrinter00.BUSY = False
                statusVar_printers_statusPrinter00.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter00.IDLE = False
                statusVar_printers_statusPrinter00.BUSY = True
                statusVar_printers_statusPrinter00.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter00.IDLE = False
                statusVar_printers_statusPrinter00.BUSY = False
                statusVar_printers_statusPrinter00.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter00.IDLE = False
                statusVar_printers_statusPrinter00.BUSY = False
                statusVar_printers_statusPrinter00.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select


        ' Status for 3D Printer 01
        Select Case Station0_moviconSend.printer01
            Case statCodeIdle
                statusVar_printers_statusPrinter01.IDLE = True
                statusVar_printers_statusPrinter01.BUSY = False
                statusVar_printers_statusPrinter01.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter01.IDLE = False
                statusVar_printers_statusPrinter01.BUSY = True
                statusVar_printers_statusPrinter01.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter01.IDLE = False
                statusVar_printers_statusPrinter01.BUSY = False
                statusVar_printers_statusPrinter01.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter01.IDLE = False
                statusVar_printers_statusPrinter01.BUSY = False
                statusVar_printers_statusPrinter01.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 02
        Select Case Station0_moviconSend.printer02
            Case statCodeIdle
                statusVar_printers_statusPrinter02.IDLE = True
                statusVar_printers_statusPrinter02.BUSY = False
                statusVar_printers_statusPrinter02.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter02.IDLE = False
                statusVar_printers_statusPrinter02.BUSY = True
                statusVar_printers_statusPrinter02.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter02.IDLE = False
                statusVar_printers_statusPrinter02.BUSY = False
                statusVar_printers_statusPrinter02.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter02.IDLE = False
                statusVar_printers_statusPrinter02.BUSY = False
                statusVar_printers_statusPrinter02.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 03
        Select Case Station0_moviconSend.printer03
            Case statCodeIdle
                statusVar_printers_statusPrinter03.IDLE = True
                statusVar_printers_statusPrinter03.BUSY = False
                statusVar_printers_statusPrinter03.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter03.IDLE = False
                statusVar_printers_statusPrinter03.BUSY = True
                statusVar_printers_statusPrinter03.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter03.IDLE = False
                statusVar_printers_statusPrinter03.BUSY = False
                statusVar_printers_statusPrinter03.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter03.IDLE = False
                statusVar_printers_statusPrinter03.BUSY = False
                statusVar_printers_statusPrinter03.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 04
        Select Case Station0_moviconSend.printer04
            Case statCodeIdle
                statusVar_printers_statusPrinter04.IDLE = True
                statusVar_printers_statusPrinter04.BUSY = False
                statusVar_printers_statusPrinter04.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter04.IDLE = False
                statusVar_printers_statusPrinter04.BUSY = True
                statusVar_printers_statusPrinter04.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter04.IDLE = False
                statusVar_printers_statusPrinter04.BUSY = False
                statusVar_printers_statusPrinter04.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter04.IDLE = False
                statusVar_printers_statusPrinter04.BUSY = False
                statusVar_printers_statusPrinter04.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 05
        Select Case Station0_moviconSend.printer05
            Case statCodeIdle
                statusVar_printers_statusPrinter05.IDLE = True
                statusVar_printers_statusPrinter05.BUSY = False
                statusVar_printers_statusPrinter05.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter05.IDLE = False
                statusVar_printers_statusPrinter05.BUSY = True
                statusVar_printers_statusPrinter05.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter05.IDLE = False
                statusVar_printers_statusPrinter05.BUSY = False
                statusVar_printers_statusPrinter05.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter05.IDLE = False
                statusVar_printers_statusPrinter05.BUSY = False
                statusVar_printers_statusPrinter05.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 06
        Select Case Station0_moviconSend.printer06
            Case statCodeIdle
                statusVar_printers_statusPrinter06.IDLE = True
                statusVar_printers_statusPrinter06.BUSY = False
                statusVar_printers_statusPrinter06.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter06.IDLE = False
                statusVar_printers_statusPrinter06.BUSY = True
                statusVar_printers_statusPrinter06.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter06.IDLE = False
                statusVar_printers_statusPrinter06.BUSY = False
                statusVar_printers_statusPrinter06.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter06.IDLE = False
                statusVar_printers_statusPrinter06.BUSY = False
                statusVar_printers_statusPrinter06.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 07
        Select Case Station0_moviconSend.printer07
            Case statCodeIdle
                statusVar_printers_statusPrinter07.IDLE = True
                statusVar_printers_statusPrinter07.BUSY = False
                statusVar_printers_statusPrinter07.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter07.IDLE = False
                statusVar_printers_statusPrinter07.BUSY = True
                statusVar_printers_statusPrinter07.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter07.IDLE = False
                statusVar_printers_statusPrinter07.BUSY = False
                statusVar_printers_statusPrinter07.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter07.IDLE = False
                statusVar_printers_statusPrinter07.BUSY = False
                statusVar_printers_statusPrinter07.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 08
        Select Case Station0_moviconSend.printer08
            Case statCodeIdle
                statusVar_printers_statusPrinter08.IDLE = True
                statusVar_printers_statusPrinter08.BUSY = False
                statusVar_printers_statusPrinter08.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter08.IDLE = False
                statusVar_printers_statusPrinter08.BUSY = True
                statusVar_printers_statusPrinter08.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter08.IDLE = False
                statusVar_printers_statusPrinter08.BUSY = False
                statusVar_printers_statusPrinter08.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter08.IDLE = False
                statusVar_printers_statusPrinter08.BUSY = False
                statusVar_printers_statusPrinter08.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 09
        Select Case Station0_moviconSend.printer09
            Case statCodeIdle
                statusVar_printers_statusPrinter09.IDLE = True
                statusVar_printers_statusPrinter09.BUSY = False
                statusVar_printers_statusPrinter09.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter09.IDLE = False
                statusVar_printers_statusPrinter09.BUSY = True
                statusVar_printers_statusPrinter09.FAULT = False
                statusVar_workstation_printerRack00 = False
            Case statCodeFault
                statusVar_printers_statusPrinter09.IDLE = False
                statusVar_printers_statusPrinter09.BUSY = False
                statusVar_printers_statusPrinter09.FAULT = True
                statusVar_workstation_printerRack00 = True
            Case Else
                statusVar_printers_statusPrinter09.IDLE = False
                statusVar_printers_statusPrinter09.BUSY = False
                statusVar_printers_statusPrinter09.FAULT = True
                statusVar_workstation_printerRack00 = True
        End Select

        ' Status for 3D Printer 10
        Select Case Station0_moviconSend.printer10
            Case statCodeIdle
                statusVar_printers_statusPrinter10.IDLE = True
                statusVar_printers_statusPrinter10.BUSY = False
                statusVar_printers_statusPrinter10.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter10.IDLE = False
                statusVar_printers_statusPrinter10.BUSY = True
                statusVar_printers_statusPrinter10.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter10.IDLE = False
                statusVar_printers_statusPrinter10.BUSY = False
                statusVar_printers_statusPrinter10.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter10.IDLE = False
                statusVar_printers_statusPrinter10.BUSY = False
                statusVar_printers_statusPrinter10.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 11
        Select Case Station0_moviconSend.printer11
            Case statCodeIdle
                statusVar_printers_statusPrinter11.IDLE = True
                statusVar_printers_statusPrinter11.BUSY = False
                statusVar_printers_statusPrinter11.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter11.IDLE = False
                statusVar_printers_statusPrinter11.BUSY = True
                statusVar_printers_statusPrinter11.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter11.IDLE = False
                statusVar_printers_statusPrinter11.BUSY = False
                statusVar_printers_statusPrinter11.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter11.IDLE = False
                statusVar_printers_statusPrinter11.BUSY = False
                statusVar_printers_statusPrinter11.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 12
        Select Case Station0_moviconSend.printer12
            Case statCodeIdle
                statusVar_printers_statusPrinter12.IDLE = True
                statusVar_printers_statusPrinter12.BUSY = False
                statusVar_printers_statusPrinter12.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter12.IDLE = False
                statusVar_printers_statusPrinter12.BUSY = True
                statusVar_printers_statusPrinter12.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter12.IDLE = False
                statusVar_printers_statusPrinter12.BUSY = False
                statusVar_printers_statusPrinter12.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter12.IDLE = False
                statusVar_printers_statusPrinter12.BUSY = False
                statusVar_printers_statusPrinter12.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 13
        Select Case Station0_moviconSend.printer13
            Case statCodeIdle
                statusVar_printers_statusPrinter13.IDLE = True
                statusVar_printers_statusPrinter13.BUSY = False
                statusVar_printers_statusPrinter13.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter13.IDLE = False
                statusVar_printers_statusPrinter13.BUSY = True
                statusVar_printers_statusPrinter13.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter13.IDLE = False
                statusVar_printers_statusPrinter13.BUSY = False
                statusVar_printers_statusPrinter13.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter13.IDLE = False
                statusVar_printers_statusPrinter13.BUSY = False
                statusVar_printers_statusPrinter13.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 14
        Select Case Station0_moviconSend.printer14
            Case statCodeIdle
                statusVar_printers_statusPrinter14.IDLE = True
                statusVar_printers_statusPrinter14.BUSY = False
                statusVar_printers_statusPrinter14.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter14.IDLE = False
                statusVar_printers_statusPrinter14.BUSY = True
                statusVar_printers_statusPrinter14.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter14.IDLE = False
                statusVar_printers_statusPrinter14.BUSY = False
                statusVar_printers_statusPrinter14.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter14.IDLE = False
                statusVar_printers_statusPrinter14.BUSY = False
                statusVar_printers_statusPrinter14.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 15
        Select Case Station0_moviconSend.printer15
            Case statCodeIdle
                statusVar_printers_statusPrinter15.IDLE = True
                statusVar_printers_statusPrinter15.BUSY = False
                statusVar_printers_statusPrinter15.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter15.IDLE = False
                statusVar_printers_statusPrinter15.BUSY = True
                statusVar_printers_statusPrinter15.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter15.IDLE = False
                statusVar_printers_statusPrinter15.BUSY = False
                statusVar_printers_statusPrinter15.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter15.IDLE = False
                statusVar_printers_statusPrinter15.BUSY = False
                statusVar_printers_statusPrinter15.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 16
        Select Case Station0_moviconSend.printer16
            Case statCodeIdle
                statusVar_printers_statusPrinter16.IDLE = True
                statusVar_printers_statusPrinter16.BUSY = False
                statusVar_printers_statusPrinter16.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter16.IDLE = False
                statusVar_printers_statusPrinter16.BUSY = True
                statusVar_printers_statusPrinter16.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter16.IDLE = False
                statusVar_printers_statusPrinter16.BUSY = False
                statusVar_printers_statusPrinter16.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter16.IDLE = False
                statusVar_printers_statusPrinter16.BUSY = False
                statusVar_printers_statusPrinter16.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 17
        Select Case Station0_moviconSend.printer17
            Case statCodeIdle
                statusVar_printers_statusPrinter17.IDLE = True
                statusVar_printers_statusPrinter17.BUSY = False
                statusVar_printers_statusPrinter17.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter17.IDLE = False
                statusVar_printers_statusPrinter17.BUSY = True
                statusVar_printers_statusPrinter17.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter17.IDLE = False
                statusVar_printers_statusPrinter17.BUSY = False
                statusVar_printers_statusPrinter17.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter17.IDLE = False
                statusVar_printers_statusPrinter17.BUSY = False
                statusVar_printers_statusPrinter17.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 18
        Select Case Station0_moviconSend.printer18
            Case statCodeIdle
                statusVar_printers_statusPrinter18.IDLE = True
                statusVar_printers_statusPrinter18.BUSY = False
                statusVar_printers_statusPrinter18.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter18.IDLE = False
                statusVar_printers_statusPrinter18.BUSY = True
                statusVar_printers_statusPrinter18.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter18.IDLE = False
                statusVar_printers_statusPrinter18.BUSY = False
                statusVar_printers_statusPrinter18.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter18.IDLE = False
                statusVar_printers_statusPrinter18.BUSY = False
                statusVar_printers_statusPrinter18.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        ' Status for 3D Printer 19
        Select Case Station0_moviconSend.printer19
            Case statCodeIdle
                statusVar_printers_statusPrinter19.IDLE = True
                statusVar_printers_statusPrinter19.BUSY = False
                statusVar_printers_statusPrinter19.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeBusy
                statusVar_printers_statusPrinter19.IDLE = False
                statusVar_printers_statusPrinter19.BUSY = True
                statusVar_printers_statusPrinter19.FAULT = False
                statusVar_workstation_printerRack01 = False
            Case statCodeFault
                statusVar_printers_statusPrinter19.IDLE = False
                statusVar_printers_statusPrinter19.BUSY = False
                statusVar_printers_statusPrinter19.FAULT = True
                statusVar_workstation_printerRack01 = True
            Case Else
                statusVar_printers_statusPrinter19.IDLE = False
                statusVar_printers_statusPrinter19.BUSY = False
                statusVar_printers_statusPrinter19.FAULT = True
                statusVar_workstation_printerRack01 = True
        End Select

        '
        ' Status for Laser Cutter
        '
        ' Status for Laser Cutter 00
        Select Case Station0_moviconSend.laserCutter00
            Case statCodeIdle
                statusVar_laserCutter_statusLaserCutter00.IDLE = True
                statusVar_laserCutter_statusLaserCutter00.BUSY = False
                statusVar_laserCutter_statusLaserCutter00.FAULT = False
                statusVar_workstation_laserCutterWorkstation = False
            Case statCodeBusy
                statusVar_laserCutter_statusLaserCutter00.IDLE = False
                statusVar_laserCutter_statusLaserCutter00.BUSY = True
                statusVar_laserCutter_statusLaserCutter00.FAULT = False
                statusVar_workstation_laserCutterWorkstation = False
            Case statCodeFault
                statusVar_laserCutter_statusLaserCutter00.IDLE = False
                statusVar_laserCutter_statusLaserCutter00.BUSY = False
                statusVar_laserCutter_statusLaserCutter00.FAULT = True
                statusVar_workstation_laserCutterWorkstation = True
            Case Else
                statusVar_laserCutter_statusLaserCutter00.IDLE = False
                statusVar_laserCutter_statusLaserCutter00.BUSY = False
                statusVar_laserCutter_statusLaserCutter00.FAULT = True
                statusVar_workstation_laserCutterWorkstation = True
        End Select

        '
        ' Status for Mobile Robots
        '
        ' Status for Mobile Robots 00
        Select Case Station0_moviconSend.mobileRobot00
            Case statCodeIdle
                statusVar_mobileRobot_statusMobileRobot00.IDLE = True
                statusVar_mobileRobot_statusMobileRobot00.BUSY = False
                statusVar_mobileRobot_statusMobileRobot00.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeBusy
                statusVar_mobileRobot_statusMobileRobot00.IDLE = False
                statusVar_mobileRobot_statusMobileRobot00.BUSY = True
                statusVar_mobileRobot_statusMobileRobot00.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeFault
                statusVar_mobileRobot_statusMobileRobot00.IDLE = False
                statusVar_mobileRobot_statusMobileRobot00.BUSY = False
                statusVar_mobileRobot_statusMobileRobot00.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
            Case Else
                statusVar_mobileRobot_statusMobileRobot00.IDLE = False
                statusVar_mobileRobot_statusMobileRobot00.BUSY = False
                statusVar_mobileRobot_statusMobileRobot00.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
        End Select

        ' Status for Mobile Robots 01
        Select Case Station0_moviconSend.mobileRobot01
            Case statCodeIdle
                statusVar_mobileRobot_statusMobileRobot01.IDLE = True
                statusVar_mobileRobot_statusMobileRobot01.BUSY = False
                statusVar_mobileRobot_statusMobileRobot01.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeBusy
                statusVar_mobileRobot_statusMobileRobot01.IDLE = False
                statusVar_mobileRobot_statusMobileRobot01.BUSY = True
                statusVar_mobileRobot_statusMobileRobot01.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeFault
                statusVar_mobileRobot_statusMobileRobot01.IDLE = False
                statusVar_mobileRobot_statusMobileRobot01.BUSY = False
                statusVar_mobileRobot_statusMobileRobot01.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
            Case Else
                statusVar_mobileRobot_statusMobileRobot01.IDLE = False
                statusVar_mobileRobot_statusMobileRobot01.BUSY = False
                statusVar_mobileRobot_statusMobileRobot01.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
        End Select

        ' Status for Mobile Robots 02
        Select Case Station0_moviconSend.mobileRobot02
            Case statCodeIdle
                statusVar_mobileRobot_statusMobileRobot02.IDLE = True
                statusVar_mobileRobot_statusMobileRobot02.BUSY = False
                statusVar_mobileRobot_statusMobileRobot02.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeBusy
                statusVar_mobileRobot_statusMobileRobot02.IDLE = False
                statusVar_mobileRobot_statusMobileRobot02.BUSY = True
                statusVar_mobileRobot_statusMobileRobot02.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeFault
                statusVar_mobileRobot_statusMobileRobot02.IDLE = False
                statusVar_mobileRobot_statusMobileRobot02.BUSY = False
                statusVar_mobileRobot_statusMobileRobot02.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
            Case Else
                statusVar_mobileRobot_statusMobileRobot02.IDLE = False
                statusVar_mobileRobot_statusMobileRobot02.BUSY = False
                statusVar_mobileRobot_statusMobileRobot02.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
        End Select

        '
        ' Status for Cobots
        '
        ' Status for Mobile Robots Cobots 00
        Select Case Station0_moviconSend.cobot00
            Case statCodeIdle
                statusVar_mobileRobot_statusMobileRobotCobot00.IDLE = True
                statusVar_mobileRobot_statusMobileRobotCobot00.BUSY = False
                statusVar_mobileRobot_statusMobileRobotCobot00.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeBusy
                statusVar_mobileRobot_statusMobileRobotCobot00.IDLE = False
                statusVar_mobileRobot_statusMobileRobotCobot00.BUSY = True
                statusVar_mobileRobot_statusMobileRobotCobot00.FAULT = False
                statusVar_workstation_mobileRobotFleet = False
            Case statCodeFault
                statusVar_mobileRobot_statusMobileRobotCobot00.IDLE = False
                statusVar_mobileRobot_statusMobileRobotCobot00.BUSY = False
                statusVar_mobileRobot_statusMobileRobotCobot00.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
            Case Else
                statusVar_mobileRobot_statusMobileRobotCobot00.IDLE = False
                statusVar_mobileRobot_statusMobileRobotCobot00.BUSY = False
                statusVar_mobileRobot_statusMobileRobotCobot00.FAULT = True
                statusVar_workstation_mobileRobotFleet = True
        End Select

        ' Status for Cobots 00
        Select Case Station0_moviconSend.cobot01
            Case statCodeIdle
                statusVar_cobot_statusCobot00.IDLE = True
                statusVar_cobot_statusCobot00.BUSY = False
                statusVar_cobot_statusCobot00.FAULT = False
                statusVar_workstation_cobotWorkstation = False
            Case statCodeBusy
                statusVar_cobot_statusCobot00.IDLE = False
                statusVar_cobot_statusCobot00.BUSY = True
                statusVar_cobot_statusCobot00.FAULT = False
                statusVar_workstation_cobotWorkstation = False
            Case statCodeFault
                statusVar_cobot_statusCobot00.IDLE = False
                statusVar_cobot_statusCobot00.BUSY = False
                statusVar_cobot_statusCobot00.FAULT = True
                statusVar_workstation_cobotWorkstation = True
            Case Else
                statusVar_cobot_statusCobot00.IDLE = False
                statusVar_cobot_statusCobot00.BUSY = False
                statusVar_cobot_statusCobot00.FAULT = True
                statusVar_workstation_cobotWorkstation = True
        End Select

        ' Status for Cobots 01
        Select Case Station0_moviconSend.cobot02
            Case statCodeIdle
                statusVar_cobot_statusCobot01.IDLE = True
                statusVar_cobot_statusCobot01.BUSY = False
                statusVar_cobot_statusCobot01.FAULT = False
                statusVar_workstation_cobotWorkstation = False
            Case statCodeBusy
                statusVar_cobot_statusCobot01.IDLE = False
                statusVar_cobot_statusCobot01.BUSY = True
                statusVar_cobot_statusCobot01.FAULT = False
                statusVar_workstation_cobotWorkstation = False
            Case statCodeFault
                statusVar_cobot_statusCobot01.IDLE = False
                statusVar_cobot_statusCobot01.BUSY = False
                statusVar_cobot_statusCobot01.FAULT = True
                statusVar_workstation_cobotWorkstation = True
            Case Else
                statusVar_cobot_statusCobot01.IDLE = False
                statusVar_cobot_statusCobot01.BUSY = False
                statusVar_cobot_statusCobot01.FAULT = True
                statusVar_workstation_cobotWorkstation = True
        End Select

        '
        ' Status for Quattro Robots
        '
        ' Status for Quattro Robot 00
        Select Case Station0_moviconSend.quattro00
            Case statCodeIdle
                statusVar_quattro_statusQuattro00.IDLE = True
                statusVar_quattro_statusQuattro00.BUSY = False
                statusVar_quattro_statusQuattro00.FAULT = False
                statusVar_workstation_quattroWorkstation = False
            Case statCodeBusy
                statusVar_quattro_statusQuattro00.IDLE = False
                statusVar_quattro_statusQuattro00.BUSY = True
                statusVar_quattro_statusQuattro00.FAULT = False
                statusVar_workstation_quattroWorkstation = False
            Case statCodeFault
                statusVar_quattro_statusQuattro00.IDLE = False
                statusVar_quattro_statusQuattro00.BUSY = False
                statusVar_quattro_statusQuattro00.FAULT = True
                statusVar_workstation_quattroWorkstation = True
            Case Else
                statusVar_quattro_statusQuattro00.IDLE = False
                statusVar_quattro_statusQuattro00.BUSY = False
                statusVar_quattro_statusQuattro00.FAULT = True
                statusVar_workstation_quattroWorkstation = True
        End Select

        '
        ' Status for Viper Robots
        '
        ' Status for Viper Robot 00
        Select Case Station0_moviconSend.viper00
            Case statCodeIdle
                statusVar_viper_statusViper00.IDLE = True
                statusVar_viper_statusViper00.BUSY = False
                statusVar_viper_statusViper00.FAULT = False
                statusVar_workstation_viperWorkstation = False
            Case statCodeBusy
                statusVar_viper_statusViper00.IDLE = False
                statusVar_viper_statusViper00.BUSY = True
                statusVar_viper_statusViper00.FAULT = False
                statusVar_workstation_viperWorkstation = False
            Case statCodeFault
                statusVar_viper_statusViper00.IDLE = False
                statusVar_viper_statusViper00.BUSY = False
                statusVar_viper_statusViper00.FAULT = True
                statusVar_workstation_viperWorkstation = True
            Case Else
                statusVar_viper_statusViper00.IDLE = False
                statusVar_viper_statusViper00.BUSY = False
                statusVar_viper_statusViper00.FAULT = True
                statusVar_workstation_viperWorkstation = True
        End Select

        ' Status for Viper Robot 01
        Select Case Station0_moviconSend.viper01
            Case statCodeIdle
                statusVar_viper_statusViper01.IDLE = True
                statusVar_viper_statusViper01.BUSY = False
                statusVar_viper_statusViper01.FAULT = False
                statusVar_workstation_viperWorkstation = False
            Case statCodeBusy
                statusVar_viper_statusViper01.IDLE = False
                statusVar_viper_statusViper01.BUSY = True
                statusVar_viper_statusViper01.FAULT = False
                statusVar_workstation_viperWorkstation = False
            Case statCodeFault
                statusVar_viper_statusViper01.IDLE = False
                statusVar_viper_statusViper01.BUSY = False
                statusVar_viper_statusViper01.FAULT = True
                statusVar_workstation_viperWorkstation = True
            Case Else
                statusVar_viper_statusViper01.IDLE = False
                statusVar_viper_statusViper01.BUSY = False
                statusVar_viper_statusViper01.FAULT = True
                statusVar_workstation_viperWorkstation = True
        End Select
        
        Thread.Sleep(sleepTime)

    Loop Until stopVar = False
End Sub
</sCode>
  <sessionName i:nil="true" />
  <slowSamplingInterval>5000</slowSamplingInterval>
  <stopCommandTimeout>2000</stopCommandTimeout>
  <threadPriority>Normal</threadPriority>
  <useAlwaysSecureConnections>false</useAlwaysSecureConnections>
  <writeTimeout>0</writeTimeout>
</ScriptDocument>